import type { Metadata } from "next";
import { Assistant } from "next/font/google";

import "./globals.css";
import Header from "../components/Header";

const assistant = Assistant({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700", "800"], // All available weights
    variable: "--font-assistant",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="he" dir="rtl">
            <body
                className={`${assistant.variable} font-assistant antialiased w-full`}
            >
                <Header />
                {children}
            </body>
        </html>
    );
}
